version: '3.5'

services:
  vpn:
    build: .
    image: mkarpusiewicz/nordvpn-client:local
    restart: unless-stopped
    networks: 
      - vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    stdin_open: true
    tty: true
    secrets:
       - nordvpn-auth
    environment:
      COUNTRY: Poland
      PROTOCOL: openvpn_udp

networks: 
  vpn:
    driver: bridge

secrets:
  nordvpn-auth:
    file: .nordvpn-auth